name: keep_alive_hotspot
description: A Flutter utility to keep iOS hotspot active.
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  audioplayers: ^5.2.1
  connectivity_plus: ^5.0.2
  flutter_local_notifications: ^17.1.0
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/silence.mp3

dependency_overrides:
  win32: ^5.13.0
